### ISSUE TITLE
Byproduct / Mainproduct issue

### ISSUE THREAD

**Issue by AkibaBoi** [Gonozal/eco-cost-calculator#3]
With the "Prepared Meat" recipe, the scrap meat is treated as the main output, and with the "Crispy Bacon" recipe, the tallows are treated as the main product.

**Comment by AkibaBoi** [comment]
There may be more of these, but those are the ones I've encountered so far

**Comment by AkibaBoi** [comment]
Suggestion to compare the output product name to the recipe name to determine the main product

**Comment by Gonozal** [comment]
Good suggestion! 
You're welcome to put up a PR yourself

If not, I'll try and get around to it in the next couple of days.

**Comment by Gonozal** [comment]
Should be fixed now :)
However, you might need to create a new profile and delete the old one to seer the changes
